baseURL = 'https://simonarnost.github.io/alephone/'
languageCode = 'en-us'
title = 'Simon Arnost'
theme = 'papermod'

copyright = 'Â© Simon Arnost'

[pagination]
  pagerSize = 10

[params]
  description = 'Personal site and blog'
  author = 'Simon Arnost'
  defaultTheme = 'dark'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  homeImage = '/images/prof_pic.jpeg'

  [params.label]
    text = ' '

  [params.homeInfoParams]
    Title = ''
    Content = """Hi! I am Simon Arnost, a Software Engineer at [Make](https://www.make.com). Based in Prague, Czech Republic.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."""

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/simonarnost'

  [[params.socialIcons]]
    name = 'linkedin'
    url = 'https://www.linkedin.com/in/simonarnost'

  [[params.socialIcons]]
    name = 'email'
    url = 'mailto:arnost.simon@gmail.com'

[[menu.main]]
  name = 'About'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'CV'
  url = '/cv/'
  weight = 2



[taxonomies]
  tag = 'tags'

[markup.highlight]
  noClasses = false
